### ISSUE TITLE
How can deploy this locally in ubuntu?

### ISSUE THREAD

**Issue by johnfelipe** [krisrs1128/stat479_s22#1]

**Comment by krisrs1128** [comment]
The site was built using the [distill package](https://pkgs.rstudio.com/distill/index.html). You can build the site using `rmarkdown::render_site()`, and it will create an `index.html`. Before it shows any of the notes though, each page in `_posts`needs to be rendered separately (using `rmarkdown::render()`).

For the record, this site is already built [here](http://krisrs1128.github.io/stat479_s22/). It also only includes new material covered this year, not material that we borrowed from the previous iteration, which is kept [here](http://krisrs1128.github.io/stat479/).

**Comment by johnfelipe** [comment]
do u have a docker sh or something for put all correctly for deploy your app?

**Comment by krisrs1128** [comment]
Sorry, I do not.

Le dim. 31 juill. 2022, à 10 h 59, felipe ***@***.***> a
écrit :
